version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-red-alert-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Jerusalem
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - bot_data:/app/data

volumes:
  bot_data:
    name: telegram-red-alert-data 