version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-red-alert-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Jerusalem
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SUPERUSER_ID=${SUPERUSER_ID}
      - ALERT_CHECK_INTERVAL=${ALERT_CHECK_INTERVAL}
      - SQLITE_DB_PATH=/app/data/db
    volumes:
      - bot_data:/app/data
      - ./debug_data:/app/data/debug

volumes:
  bot_data:
    name: telegram-red-alert-data 